name: fion
channels:
- conda-forge
dependencies:
- networkx
- numpy
- pandas
- xlrd
- openpyxl
- pyomo
- glpk
- pyshp
- shapely
- basemap
- pyproj
- fiona
- geopy
- geopandas
- plotly
- networkx
- psycopg2
- sqlalchemy
- python-igraph
- pip:


