# This is a conda environment setup file.
# Mainly it is used by readthedocs to create a virt-env for rivus and 
# install the dependencies. 
# Note: geopandas is from pip, so that it does not mess up the fiona install.
# Note: You could also install from this with 
# > conda env create -f environment.yml
name: rivus
channels:
- conda-forge
dependencies:
  - python=3.5 # can change in future
  - numpy
  - pandas
  - xlrd
  - openpyxl
  - pyomo
  - glpk
  - pyshp
  - shapely
  - basemap
  - pyproj
  - geopy
  - plotly
  - networkx
  - psycopg2
  - sqlalchemy
  - python-igraph # it works on the Linux RtD server.
  - pip:
      - geopandas
